spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=true&serverSslCert=/path/to/server-cert.pem
    username: root
    password: root

  # JPA settings
  jpa.hibernate.ddl_auto: create
